### ISSUE TITLE
Fix start run behavior for two PTSes

### ISSUE THREAD

**Issue by KKopyscinski** [intel/auto-pts#513]
On launch server is opening single PTS instance. Then, if client requests opening second one on run start, the first instance, already created is restarted and second one is opened. After run both instances are still opened. If client starts second run, still, the first instance is restarted, but not the second. This causes server to crash with error:
```
Traceback (most recent call last):
  File "C:\Users\krzys\auto-pts\autoptsserver.py", line 349, in <module>
    raise Exception(exceptions)
Exception: Recovery request
Recovery request
```
and client to hang up on recovery:
```
(139765204006704) Starting PTS 192.168.199.129:65000 ...
(139765204007568) Starting PTS 192.168.199.129:65002 ...
<Fault 1: "<class 'pywintypes.com_error'>:(-2147352567, 'Wystąpił wyjątek.', (0, 'PTS', '(HRESULT:0x849C0043) Error HResult!', None, 0, -2070151101), None)">

<Fault 1: "<class 'pywintypes.com_error'>:(-2147352567, 'Wystąpił wyjątek.', (0, 'PTS', '(HRESULT:0x849C0043) Error HResult!', None, 0, -2070151101), None)">
<Fault 1: "<class 'pywintypes.com_error'>:(-2147352567, 'Wystąpił wyjątek.', (0, 'PTS', '(HRESULT:0x849C0043) Error HResult!', None, 0, -2070151101), None)">

Traceback (most recent call last):
  File "/home/krzysiek/auto-pts/autoptsclient_common.py", line 1140, in start
    self.main()
  File "/home/krzysiek/auto-pts/autoptsclient_common.py", line 1187, in main
    ptses = init_pts(args, tc_db_table_name)
  File "/home/krzysiek/auto-pts/autoptsclient_common.py", line 481, in init_pts
    raise Exception(exeption_msg, proxy_list)
Exception: ('<Fault 1: "<class \'pywintypes.com_error\'>:(-2147352567, \'Wystąpił wyjątek.\', (0, \'PTS\', \'(HRESULT:0x849C0043) Error HResult!\', None, 0, -2070151101), None)">\n<Fault 1: "<class \'pywintypes.com_error\'>:(-2147352567, \'Wystąpił wyjątek.\', (0, \'PTS\', \'(HRESULT:0x849C0043) Error HResult!\', None, 0, -2070151101), None)">\n', [<ServerProxy for 192.168.199.129:65000/>, <ServerProxy for 192.168.199.129:65002/>])
Attempting to recover autoptsserver
Attempting to recover autoptsserver
(139765204007424) Starting PTS 192.168.199.129:65000 ...
(139765204005168) Starting PTS 192.168.199.129:65002 ...
```

Workaround: closing PTS instance manually before second run

**Comment by mkasenberg** [comment]
I will try to fix it.
